# -*- coding: utf-8 -*-
"""TASK 04_PANDAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Obn-N1uJpP4Df0LTSHze0LPz-Mwld_Zz
"""

#Loading Facebook ads dataset
import pandas as pd
df = pd.read_csv("2024_fb_ads_president_scored_anon.csv", engine='python')
df.describe()

import pandas as pd
df = pd.read_csv("2024_fb_ads_president_scored_anon.csv")
df.value_counts()

import pandas as pd
df = pd.read_csv("2024_fb_ads_president_scored_anon.csv")
df.nunique()

#Loading Facebook posts dataset
import pandas as pd
df = pd.read_csv("2024_fb_posts_president_scored_anon.csv")
df.describe()

import pandas as pd
df = pd.read_csv("2024_fb_posts_president_scored_anon.csv")
df.value_counts()

import pandas as pd
df = pd.read_csv("2024_fb_posts_president_scored_anon.csv")
df.nunique()

#Loading Twitter posts dataset
import pandas as pd
df = pd.read_csv("2024_tw_posts_president_scored_anon.csv")
df.describe()

import pandas as pd
df = pd.read_csv("2024_tw_posts_president_scored_anon.csv")
df.value_counts()

import pandas as pd
df = pd.read_csv("2024_tw_posts_president_scored_anon.csv")
df.nunique()